### ISSUE TITLE
Support seeds

### ISSUE THREAD

**Issue by RangerMauve** [Trott/cumberbatch-name#2]
It'd be nice if you used a random number generator that took a seed, that way there would be a way to have consistent results if one were so interested.

**Comment by Trott** [comment]
I'm inclined to keep the API surface small unless there's a compelling use case for expanding it. 

I can see this being useful for the CLI so people can have what are essentially permalinks. One issue is that you won't get consistent results across different versions because the list of name components is different across versions.

For the API use, I'm not sure this is valuable. You can cache the result yourself.

**Comment by RangerMauve** [comment]
My use case was to use browser fingerprinting to generate a name for users when they join a chat. I suppose I could just save the value on the server somewhere rather than have it generated on the fly.

**Comment by Trott** [comment]
That sounds like a plan. Cool.
